### ISSUE TITLE
Gem overwritten on rubygems.org?

### ISSUE THREAD

**Issue by matt-richardson** [ruby/fiddle#1]
I've been tracking down why my build is failing, and it appears that all old versions of fiddle on rubygems.org have been yanked.

Looking closer, it appears that this is a completely different gem to the previous one, which appears to be https://github.com/bsm/fiddle.

What's happened to the old gem?

**Comment by matt-richardson** [comment]
The more i look into this, the more I'm confused. I may have completely got the wrong end of the stick here...

**Comment by hsbt** [comment]
Hi, As first, sorry your inconvenient experience. 

`Fiddle` is standard library of Ruby core since 2010. If Users invoke `gem i fiddle`, It broke standard library and their ruby environment. I hope to safe this situation.

So I got ownership of `fiddle` namespace from author of `bsm/fiddle`. Unfortunetely, I removed exists gems and ship new gem. 

You need fork `bsm/fiddle` and ship another name for your application.
